"""DataHub source adapter implementations."""

from .akshare import (
    AKSHARE_SOURCE_ID,
    AKSHARE_SOURCE_NAME,
    MACRO_POLICY_SOURCE_ID,
    MACRO_POLICY_SOURCE_NAME,
    AkshareAShareDailyBarAdapter,
    AkshareAShareCorporateActionsAdapter,
    AkshareAShareInstrumentMasterAdapter,
    AkshareAShareCapitalFlowSnapshotAdapter,
    AkshareAShareValuationSnapshotAdapter,
    AkshareChinaMacroAdapter,
    AkshareFundProfileAdapter,
    AkshareETFFundHoldingsAdapter,
    AkshareETFFundNavSnapshotAdapter,
    AkshareGlobalEquitySnapshotAdapter,
    AkshareNewsEventsAdapter,
    AkshareIndexDailyBarAdapter,
    AkshareIndexConstituentsAdapter,
    AkshareSectorMembershipAdapter,
    AkshareSectorMasterAdapter,
    AkshareSectorDailyBarAdapter,
    AkshareHKInstrumentMasterAdapter,
    AkshareHKCorporateActionsAdapter,
    AkshareHKValuationSnapshotAdapter,
    AkshareAShareFinancialDataAdapter,
    AkshareHKFinancialDataAdapter,
    AkshareHKDailyBarAdapter,
    AkshareETFDailyBarAdapter,
    AkshareAShareTradingCalendarAdapter,
)
from .policy import (
    MacroPolicyDocumentsAdapter,
)
from .hkex import (
    HKEX_SOURCE_ID,
    HKEX_SOURCE_NAME,
    HkexCompanyAnnouncementsAdapter,
    HkexHKTradingCalendarAdapter,
)

__all__ = [
    "AKSHARE_SOURCE_ID",
    "AKSHARE_SOURCE_NAME",
    "MACRO_POLICY_SOURCE_ID",
    "MACRO_POLICY_SOURCE_NAME",
    "HKEX_SOURCE_ID",
    "HKEX_SOURCE_NAME",
    "AkshareAShareDailyBarAdapter",
    "AkshareAShareCorporateActionsAdapter",
    "AkshareAShareInstrumentMasterAdapter",
    "AkshareAShareCapitalFlowSnapshotAdapter",
    "AkshareAShareValuationSnapshotAdapter",
    "AkshareChinaMacroAdapter",
    "AkshareFundProfileAdapter",
    "AkshareETFFundHoldingsAdapter",
    "AkshareETFFundNavSnapshotAdapter",
    "AkshareGlobalEquitySnapshotAdapter",
    "AkshareNewsEventsAdapter",
    "AkshareIndexDailyBarAdapter",
    "AkshareIndexConstituentsAdapter",
    "AkshareSectorMembershipAdapter",
    "AkshareSectorMasterAdapter",
    "AkshareSectorDailyBarAdapter",
    "AkshareHKInstrumentMasterAdapter",
    "AkshareHKCorporateActionsAdapter",
    "AkshareHKValuationSnapshotAdapter",
    "AkshareAShareFinancialDataAdapter",
    "AkshareHKFinancialDataAdapter",
    "AkshareHKDailyBarAdapter",
    "AkshareETFDailyBarAdapter",
    "AkshareAShareTradingCalendarAdapter",
    "MacroPolicyDocumentsAdapter",
    "HkexCompanyAnnouncementsAdapter",
    "HkexHKTradingCalendarAdapter",
]
